services:
  slmyer:
    container_name: slmyer
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app # 挂载代码目录
      - /app/node_modules # 避免 node_modules 被覆盖
